**Exercise 1**

In [48]:
import numpy as np

array1 = np.array([88,23,39,41])
array1

array([88, 23, 39, 41])

In [49]:
array1.ndim

1

In [50]:
array1.size

4

In [51]:
array1.shape

(4,)

In [52]:
array1.dtype

dtype('int32')

In [17]:
array2 = np.array([[76.4,21.7,38.4],[41.2,52.8,68.9]])
array2

array([[76.4, 21.7, 38.4],
       [41.2, 52.8, 68.9]])

In [20]:
array2.ndim

2

In [21]:
array2.size

6

In [22]:
array2.shape

(2, 3)

In [23]:
array2.dtype

dtype('float64')

In [43]:
array3 = np.array([[12],[4],[9],[8]])
array3

array([[12],
       [ 4],
       [ 9],
       [ 8]])

In [44]:
array3.ndim

2

In [45]:
array3.size

4

In [46]:
array3.shape

(4, 1)

In [47]:
array3.dtype

dtype('int32')

**Exercise 2**

In [62]:
M_diag = np.diag(range(int(50)))
M_diag

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

In [63]:
M_diag.ndim

2

In [64]:
M_diag.size

2500

In [65]:
M_diag.shape

(50, 50)

In [66]:
M_diag.dtype

dtype('int32')

**Exercise 3**

In [70]:
#array(20,5) float [1,10] equiespaciados
np.linspace(1,10, 100).reshape(20,5)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636],
       [ 1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727],
       [ 2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818],
       [ 3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909],
       [ 4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ],
       [ 5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091],
       [ 6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182],
       [ 6.90909091,  7.        ,  7.0

In [71]:
np.random.normal(1,2,128)

array([ 1.05600473e+00, -4.01626074e+00,  4.87905847e+00,  1.60593540e+00,
        1.47882033e+00, -8.42388266e-01,  2.37609562e-01, -2.69026270e-01,
        4.03831851e+00, -1.04556969e+00,  5.21825564e-01,  1.81415492e+00,
        1.79160187e+00, -9.00553272e-01,  5.78370279e-01, -4.11259506e-01,
        2.70275489e+00, -3.48289909e+00,  1.79351065e+00,  2.22276033e+00,
       -9.78096584e-01,  4.97391753e-01,  4.43518127e+00,  9.16721150e-01,
        1.22370725e+00, -8.99945888e-01,  2.55860211e+00,  4.70097773e+00,
       -1.68760788e+00, -2.41296526e+00,  5.37425183e+00,  7.77056227e-01,
       -1.42136662e+00, -1.91765611e-03,  1.49249753e+00, -4.30460766e+00,
        5.98996197e-01,  3.34037184e+00, -2.79935190e+00, -4.30550928e-03,
        2.17741343e+00,  9.08655301e-01,  8.30161416e-01,  1.84426138e+00,
        1.22162304e+00,  2.93433544e-01, -9.17880553e-01,  4.14994961e+00,
        2.47966958e+00,  1.20759968e+00,  1.26994912e+00, -6.18074288e-01,
        3.18912219e+00,  

In [73]:
np.random.choice(['2','x','1'],size=15,p=[.5,.3,.2])

array(['2', '1', 'x', 'x', '1', '2', 'x', 'x', 'x', '1', 'x', '2', '1',
       '2', '1'], dtype='<U1')

**Exercise 4**