**Exercise 1**

In [48]:
import numpy as np

array1 = np.array([88,23,39,41])
array1

array([88, 23, 39, 41])

In [49]:
array1.ndim

1

In [50]:
array1.size

4

In [51]:
array1.shape

(4,)

In [52]:
array1.dtype

dtype('int32')

In [17]:
array2 = np.array([[76.4,21.7,38.4],[41.2,52.8,68.9]])
array2

array([[76.4, 21.7, 38.4],
       [41.2, 52.8, 68.9]])

In [20]:
array2.ndim

2

In [21]:
array2.size

6

In [22]:
array2.shape

(2, 3)

In [23]:
array2.dtype

dtype('float64')

In [43]:
array3 = np.array([[12],[4],[9],[8]])
array3

array([[12],
       [ 4],
       [ 9],
       [ 8]])

In [44]:
array3.ndim

2

In [45]:
array3.size

4

In [46]:
array3.shape

(4, 1)

In [47]:
array3.dtype

dtype('int32')

**Exercise 2**

In [62]:
M_diag = np.diag(range(int(50)))
M_diag

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

In [63]:
M_diag.ndim

2

In [64]:
M_diag.size

2500

In [65]:
M_diag.shape

(50, 50)

In [66]:
M_diag.dtype

dtype('int32')

**Exercise 3**

In [70]:
#array(20,5) float [1,10] equiespaciados
np.linspace(1,10, 100).reshape(20,5)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636],
       [ 1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727],
       [ 2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818],
       [ 3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909],
       [ 4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ],
       [ 5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091],
       [ 6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182],
       [ 6.90909091,  7.        ,  7.0

In [71]:
np.random.normal(1,2,128)

array([ 1.05600473e+00, -4.01626074e+00,  4.87905847e+00,  1.60593540e+00,
        1.47882033e+00, -8.42388266e-01,  2.37609562e-01, -2.69026270e-01,
        4.03831851e+00, -1.04556969e+00,  5.21825564e-01,  1.81415492e+00,
        1.79160187e+00, -9.00553272e-01,  5.78370279e-01, -4.11259506e-01,
        2.70275489e+00, -3.48289909e+00,  1.79351065e+00,  2.22276033e+00,
       -9.78096584e-01,  4.97391753e-01,  4.43518127e+00,  9.16721150e-01,
        1.22370725e+00, -8.99945888e-01,  2.55860211e+00,  4.70097773e+00,
       -1.68760788e+00, -2.41296526e+00,  5.37425183e+00,  7.77056227e-01,
       -1.42136662e+00, -1.91765611e-03,  1.49249753e+00, -4.30460766e+00,
        5.98996197e-01,  3.34037184e+00, -2.79935190e+00, -4.30550928e-03,
        2.17741343e+00,  9.08655301e-01,  8.30161416e-01,  1.84426138e+00,
        1.22162304e+00,  2.93433544e-01, -9.17880553e-01,  4.14994961e+00,
        2.47966958e+00,  1.20759968e+00,  1.26994912e+00, -6.18074288e-01,
        3.18912219e+00,  

In [73]:
np.random.choice(['2','x','1'],size=15,p=[.5,.3,.2])

array(['2', '1', 'x', 'x', '1', '2', 'x', 'x', 'x', '1', 'x', '2', '1',
       '2', '1'], dtype='<U1')

**Exercise 4**

In [75]:
original_matrix = np.array([[17,12,31],[49,11,51],[21,31,62],[63,75,22]])
original_matrix

array([[17, 12, 31],
       [49, 11, 51],
       [21, 31, 62],
       [63, 75, 22]])

In [88]:
row = original_matrix[3,:]
matrix2 = np.delete(original_matrix,3,0)
matrix2 = np.append(matrix2,row.reshape(3,-1),axis=1)
matrix2

array([[17, 12, 31, 63],
       [49, 11, 51, 75],
       [21, 31, 62, 22]])

In [89]:
matrix3 = matrix2
matrix3[1,0:3] = 49
matrix3[:,3] = 63
matrix3

array([[17, 12, 31, 63],
       [49, 49, 49, 63],
       [21, 31, 62, 63]])

**Exercise 5**

In [91]:
matrix = np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
matrix

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [97]:
odds_values = matrix[matrix%2 != 0]
odds_values

array([11, 13, 15, 17, 19, 21])

**Exercise 6**

In [116]:
or_matrix = np.random.randint(0,100, size=(10,10))
or_matrix

array([[32, 26,  2, 83, 45, 70, 92, 68, 24, 74],
       [60, 56, 26, 73, 35, 25, 33, 60, 51, 50],
       [89, 19, 54, 15, 41,  2, 73, 80, 48, 56],
       [13, 41, 35, 96, 89, 37, 28, 72, 84, 25],
       [90, 70, 90, 85,  5, 29, 31, 54,  6, 21],
       [63, 71, 35, 86, 36, 28, 49, 74, 30, 56],
       [ 3, 25, 62,  0, 64, 40, 12, 36, 13, 38],
       [75, 65, 76, 83, 34, 58, 70, 10, 69, 68],
       [13, 98, 91,  9,  3, 65, 47, 88,  3,  1],
       [26, 75, 76, 39,  7,  3, 16,  0, 80, 99]])

In [117]:
matrix1 = or_matrix.copy()
matrix1[np.diag_indices(matrix1.shape[0])] = 50
matrix1

array([[50, 26,  2, 83, 45, 70, 92, 68, 24, 74],
       [60, 50, 26, 73, 35, 25, 33, 60, 51, 50],
       [89, 19, 50, 15, 41,  2, 73, 80, 48, 56],
       [13, 41, 35, 50, 89, 37, 28, 72, 84, 25],
       [90, 70, 90, 85, 50, 29, 31, 54,  6, 21],
       [63, 71, 35, 86, 36, 50, 49, 74, 30, 56],
       [ 3, 25, 62,  0, 64, 40, 50, 36, 13, 38],
       [75, 65, 76, 83, 34, 58, 70, 50, 69, 68],
       [13, 98, 91,  9,  3, 65, 47, 88, 50,  1],
       [26, 75, 76, 39,  7,  3, 16,  0, 80, 50]])

In [118]:
matrix2 = or_matrix.copy()
matrix2[matrix2>50] = 100
matrix2

array([[ 32,  26,   2, 100,  45, 100, 100, 100,  24, 100],
       [100, 100,  26, 100,  35,  25,  33, 100, 100,  50],
       [100,  19, 100,  15,  41,   2, 100, 100,  48, 100],
       [ 13,  41,  35, 100, 100,  37,  28, 100, 100,  25],
       [100, 100, 100, 100,   5,  29,  31, 100,   6,  21],
       [100, 100,  35, 100,  36,  28,  49, 100,  30, 100],
       [  3,  25, 100,   0, 100,  40,  12,  36,  13,  38],
       [100, 100, 100, 100,  34, 100, 100,  10, 100, 100],
       [ 13, 100, 100,   9,   3, 100,  47, 100,   3,   1],
       [ 26, 100, 100,  39,   7,   3,  16,   0, 100, 100]])

In [119]:
matrix3 = or_matrix.copy()
matrix3[matrix3<50] = 0
matrix3

array([[ 0,  0,  0, 83,  0, 70, 92, 68,  0, 74],
       [60, 56,  0, 73,  0,  0,  0, 60, 51, 50],
       [89,  0, 54,  0,  0,  0, 73, 80,  0, 56],
       [ 0,  0,  0, 96, 89,  0,  0, 72, 84,  0],
       [90, 70, 90, 85,  0,  0,  0, 54,  0,  0],
       [63, 71,  0, 86,  0,  0,  0, 74,  0, 56],
       [ 0,  0, 62,  0, 64,  0,  0,  0,  0,  0],
       [75, 65, 76, 83,  0, 58, 70,  0, 69, 68],
       [ 0, 98, 91,  0,  0, 65,  0, 88,  0,  0],
       [ 0, 75, 76,  0,  0,  0,  0,  0, 80, 99]])

In [120]:
or_matrix2 = np.random.randint(0,100, size=(10,10))
or_matrix2[np.diag_indices(or_matrix2.shape[0])] = 50
or_matrix2[or_matrix2>50] = 100
or_matrix2[or_matrix2<50] = 0
or_matrix2

array([[ 50,   0,   0,   0, 100,   0,   0,   0, 100, 100],
       [  0,  50, 100, 100,   0,   0, 100, 100, 100,   0],
       [  0, 100,  50,   0,   0, 100,   0, 100,   0, 100],
       [100,   0, 100,  50,   0, 100,   0,   0, 100,   0],
       [  0, 100, 100,   0,  50, 100,   0, 100,   0, 100],
       [100, 100, 100,   0,   0,  50, 100,   0,   0, 100],
       [  0, 100, 100, 100, 100,   0,  50, 100,   0, 100],
       [  0, 100, 100, 100,   0, 100,   0,  50,   0, 100],
       [  0, 100,   0,   0, 100,   0,   0,   0,  50, 100],
       [100, 100,   0,   0, 100, 100, 100,   0, 100,  50]])

**Exercise 7**

In [121]:
k = 20
theta = 2*np.pi
right_part = np.sin(theta)/theta
right_part

-3.8981718325193755e-17

In [124]:
left_part = np.arange(1,k, dtype='float64')
left_part = np.cos(theta/np.power(2,left_part))
left_part = np.prod(left_part)
left_part

-3.8981718326126866e-17

**Exercise 8**

In [138]:
matrix1 = np.random.uniform(0,1000,size=(20,20))
matrix2 = np.random.uniform(0,1000,size=(20,20))

In [144]:
med = np.vectorize(lambda a, b: (a + b) / 2)
%timeit med(matrix1,matrix2)

226 µs ± 8.59 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [140]:
%timeit (matrix1+matrix2)/2

5.85 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**Exercise 9**

In [146]:
matrix = np.array([[1,2],[3,5]])
matrix

array([[1, 2],
       [3, 5]])

In [150]:
iden = np.eye(2)
iden

array([[1., 0.],
       [0., 1.]])

In [151]:
np.dot(matrix,matrix)-6*matrix-iden

array([[0., 0.],
       [0., 0.]])

**Exercise 10**

In [153]:
A = np.array([[1,-2,1],[3,0,1]])
B = np.array([[4,0,-1],[-2,1,0]])

In [155]:
l_p1 = (A+B).T
l_p1

array([[ 5,  1],
       [-2,  1],
       [ 0,  1]])

In [157]:
r_p1 = A.T+B.T
r_p1

array([[ 5,  1],
       [-2,  1],
       [ 0,  1]])

In [158]:
l_p2 = (3*A).T
l_p2

array([[ 3,  9],
       [-6,  0],
       [ 3,  3]])

In [159]:
r_p2 = 3*A.T
r_p2

array([[ 3,  9],
       [-6,  0],
       [ 3,  3]])

**Exercise 11**

In [161]:
A = np.array([[4,5,-1],[-3,-4,1],[-3,-4,0]])

In [169]:
np.linalg.matrix_power(A,9)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Exercise 12**

In [174]:
A = np.array([[3,4,-1],[5,-2,1],[2,-2,1]])
A

array([[ 3,  4, -1],
       [ 5, -2,  1],
       [ 2, -2,  1]])

In [175]:
B = np.array([8,4,1]).reshape(3,-1)
B

array([[8],
       [4],
       [1]])

In [176]:
np.linalg.solve(A,B)

array([[1.],
       [2.],
       [3.]])